[package]
name = "notes_training"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
holy_rnns = {path = "../holy_rnns"}
midiparser = { path = "../midiparser" }
